### ISSUE TITLE
Published to RubyGems?

### ISSUE THREAD

**Issue by vyder** [MGerrior/shoulda-whenever#1]
Any particular reason why this gem isn't published yet?

I'm using a fork to work around it, but I'm curious.

**Comment by MGerrior** [comment]
I wouldn't say there is a good reason it isn't published. I had extracted it out of another project and didn't expect too many other people to use it so I didn't bother publishing it.

On that note, I'll look into publishing it today so people don't have to fork it. Thanks for showing interest in the project.

**Comment by MGerrior** [comment]
Should be able to find the gem via RubyGems now at version 0.0.1 https://rubygems.org/gems/shoulda-whenever

**Comment by vyder** [comment]
I see. Yeah I ran into the same problem yesterday - accidentally changed my schedule and committed it without noticing because all my tests passed. Figured that was behavior worth writing a test for. Google led me to your devpost.

Thanks for publishing it 😊
