### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sean-wedig** [MGerrior/shoulda-whenever#3]
This looks like a great gem, and my team is very interested in using it... however, we're blocked without an explicit license.  Can you please publish the licensing used for this gem in something like a `LICENSE` file?

**Comment by MGerrior** [comment]
Hey @seanwedig , I'm happy to hear that! I added an MIT license in the `LICENSE` file of master. Let me know if you need me to republish the gem (possibly with a version bump to 0.0.3) so that the actual gem contains the license file when installed.

Thanks!

**Comment by sean-wedig** [comment]
Thank you for the (very) rapid response!  We're poking at it now.

**Comment by sean-wedig** [comment]
I think just the explicit license file will work for us.  Thank you for your support!
